version: "3.3"
services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    depends_on:
      - db
      - selenium
    environment:
      - POSTGRES_HOST=db
    volumes:
      - type: bind
        source: .
        target: /hello
      - type: volume
        source: dot-mix
        target: /home/hello/.mix
      - type: volume
        source: dot-hex
        target: /home/hello/.hex

  db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data

  selenium:
    image: selenium/standalone-firefox:3
    volumes:
      - /dev/shm:/dev/shm

volumes:
  db:
  dot-mix:
  dot-hex:
